name: game_friend_finder
description: Flutter with Firebase project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alert_dialogs:
    git:
      url: https://github.com/ska2519/codewithandrea_flutter_packages
      path: packages/alert_dialogs
  custom_buttons:
    git:
      url: https://github.com/ska2519/codewithandrea_flutter_packages
      path: packages/custom_buttons
  email_password_sign_in_ui:
    git:
      url: https://github.com/ska2519/codewithandrea_flutter_packages
      path: packages/email_password_sign_in_ui
  firestore_service:
    git:
      url: https://github.com/ska2519/codewithandrea_flutter_packages
      path: packages/firestore_service

  cupertino_icons: ^1.0.1
  font_awesome_flutter:
  line_awesome_flutter:

  logger: ^0.9.4
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  google_sign_in: ^4.5.6
  flutter_riverpod: ^0.12.1
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  flutter_svg: ^0.19.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/profile_woman_images/
  fonts:
    - family: Nanum
      fonts:
        - asset: fonts/NanumGothic-Regular.ttf
        - asset: fonts/NanumGothic-Bold.ttf
          weight: 700
        - asset: fonts/NanumGothic-ExtraBold.ttf
          weight: 800
